name: run vnc

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Preparing environment...
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: chmod +x ./setup.sh && ./setup.sh

#     - name: Starting VNC Server...
#       run: export PATH=$PATH:/opt/TurboVNC/bin && cd $HOME && vncserver :1 -geometry 1280x768 -depth 16 -rfbport 7582

    - name: Creating tunnel with ngrok...
      run: curl -s http://localhost:4040/api/tunnels

    - name: loop
      run: tail -F ./setup.sh
